function main() {
  // Bad Luck
  return "running app";
}

main().then(res => console.log(res).catch(err => console.error(err))
